In [1]:
import numpy as np
import numba as nb
import matplotlib.pyplot as plt
import time

In [2]:
def benchmark(f, n: int or float = 10e5, args: tuple = None, kwargs: dict = None) -> np.array:
    if args is None:
        args = ()
    if kwargs is None:
        kwargs = {}
    
    start = time.process_time()
    for _ in range(int(n)):
        f(*args, **kwargs)
    end = time.process_time()
    return (end - start)/n

In [3]:
def test_matmul(f):
    A = np.random.rand(10,2)
    B = np.random.rand(2,5)
    C = np.zeros((A.shape[0], B.shape[1]))
    f(A, B, C)
    return np.max(np.abs(np.dot(A, B) - C))

def benchmark_matmul(f, Ns, n):
    times = []
    for N in Ns:
        A = np.random.rand(N,N)
        B = np.random.rand(N,N)
        C = np.zeros((N, N))
        times.append(benchmark(f, n, args=(A, B, C)))
    return times

In [39]:
def laplas_1(U, D, h=1):
    K, J = U.shape
    
    for k in range(K):
        for j in range(J):
            D[k,j] = (U[(k-1) % K,j%J] + U[(k+1) % K,j % J] - 4*U[k%K,j%J] + U[k%K,(j+1)%J]+U[k%K,(j-1)%J])/h

In [19]:
A = np.random.rand(2,2)
ind = np.arange(2)
A

array([[0.8262718 , 0.29658604],
       [0.70881172, 0.79755754]])

In [20]:
A[ind, 1]

array([0.29658604, 0.79755754])

In [21]:
A[ind, ind]

array([0.8262718 , 0.79755754])

In [23]:
A[ind]

array([[0.8262718 , 0.29658604],
       [0.70881172, 0.79755754]])

In [29]:
(11) % 10

1

In [46]:
U = np.eye(3)
D = np.zeros((3,3))
laplas_1(U,D)

(3, 3)


In [47]:
D

array([[-4.,  2.,  2.],
       [ 2., -4.,  2.],
       [ 2.,  2., -4.]])

In [108]:
def create_D(D, N=3, M=3):
    pattern_1 = np.zeros((M,M))
    pattern_1[0,0] = -4
    pattern_1[0,1] = 1
    pattern_1[0,-1] = 1
    for n in range(M-1):
        pattern_1[n+1] = np.roll(pattern_1[0],n+1)

    pattern_2 = np.eye(M,M)
    pattern_2
    
    for n in range(N):
        D[M*n:M*(n+1),M*n:M*(n+1)] = pattern_1
        for m in range(M):
            D[M*n+m, (M*(n+1)+m) % (M*N)] = 1
            D[M*n+m, (M*(n+2)+m) % (M*N)] = 1

N, M = 3, 3
D = np.zeros((N*M,N*M))
create_D(D,N,M)
D

array([[-4.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 1., -4.,  1.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 1.,  1., -4.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0., -4.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  1., -4.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  1., -4.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  0., -4.,  1.,  1.],
       [ 0.,  1.,  0.,  0.,  1.,  0.,  1., -4.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  1.,  1., -4.]])

In [170]:
def create_D_slice(D, N=3, M=3):
    D.reshape((N,M,N,M))ca
    diag_ind = np.arange(N*M)
#     up_diag = diag_ind[]
    D[diag_ind, diag_ind] = -4
    D[diag_ind[:-1], diag_ind[1:]] = 1
    D[diag_ind[1:], diag_ind[:-1]] = 1
#     for i in range(N):
        
#     D[diag_ind, M:M*N:M] =1
    
N, M = 3, 3
D = np.zeros((N*M,N*M))
create_D_slice(D,N,M)
D

array([[-4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -4.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -4.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -4.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -4.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -4.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -4.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -4.]])

In [141]:
N, M = 10,10
D = np.zeros((N*M,N*M))
benchmark(create_D, n=10e3, kwargs={'D': D, 'N':N,'M':M})

0.00010625

In [ ]:
D = np.zeros(N,M,N,M)
def create_D_4D(D, N=3, M=3):
    for n in range(N):
        for m in range(M)
        D[n,m,]
    
D.reshape(N*M,N*M)

In [147]:
A = np.arange(10)
A[]

array([0, 2, 4, 6, 8])